"""initial migration

Revision ID: 3b36ac46ae47
Revises: 
Create Date: 2022-12-15 16:25:53.405157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b36ac46ae47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('meet_loc', sa.String(length=250), nullable=True),
    sa.Column('time', sa.String(length=4), nullable=True),
    sa.Column('meet_time', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.create_table('fixture',
    sa.Column('fixtureId', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('home_away', sa.String(length=4), nullable=True),
    sa.Column('fixture_info', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_info'], ['fixture_info.id'], ),
    sa.PrimaryKeyConstraint('fixtureId')
    )
    op.create_table('playedGames',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('fixtureId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixtureId'], ['fixture.fixtureId'], ),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playedGames')
    op.drop_table('fixture')
    op.drop_table('member')
    op.drop_table('fixture_info')
    # ### end Alembic commands ###
