"""empty message

Revision ID: cfea1d9a03c2
Revises: 3b36ac46ae47
Create Date: 2022-12-15 17:56:55.522375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfea1d9a03c2'
down_revision = '3b36ac46ae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    with op.batch_alter_table('fixture_info', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))

    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
