"""empty message

Revision ID: d4d3e336583b
Revises: cfea1d9a03c2
Create Date: 2022-12-16 15:12:37.727563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d3e336583b'
down_revision = 'cfea1d9a03c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fixture_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixture_info', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'fixture_info', ['fixture_info'], ['id'])

    # ### end Alembic commands ###
